name: Python uppercase

on:
  push: 
    paths:
      - "py-upper/**"
      - ".github/workflows/python-uppercase.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -V
      - name: Download application code
        uses: actions/checkout@v4
      - name: List directory
        run: ls -lR
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Check python version
        run: python -V          
      - name: Install requirements
        run: pip install -r py-upper/requirements.txt
      - name: Run tests
        run: pytest
