name: Python uppercase

on:
  push: 
    paths:
      - "py-upper/**"
      - ".github/workflows/python-uppercase.yml"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Display variables
        run: |
           echo "${{runner.os}}"
      - name: Check python version
        run: python -V
      - name: Download application code
        uses: actions/checkout@v4
      - name: Configure cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-pip-
      - name: List directory
        run: ls -lR
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.0-beta.3' 
      - name: Check python version
        run: python -V          
      # - name: Install requirements
      #   run: pip install -r py-upper/requirements.txt
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
          
      - name: Run tests
        run: pytest
        working-directory: py-upper
        
