name: Testing security

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "show env"
        run: env
      - name: "status of authentication"
        run: gh auth status
      - name: Checkout
        uses: actions/checkout@v4
      - name: "list workflows"
        run: gh workflow list
