name: Testing security

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "show env"
        run: env
      - name: "status of authentication"
        run: gh auth status
        env: 
          GH_TOKEN: "${{ secrets.MY_TOKEN }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: "list workflows"
        run: gh workflow list
        env: 
          GH_TOKEN: "${{ secrets.MY_TOKEN }}"        
